"""Plain-MLP baseline on the core/annulus classification task of Berndt & Stuhmer, sec. 4.1.

Data (``generate_data``, ported verbatim from
``approximate-equivariance-projection/experiments/section_4_1_mlp/src/run/
so2_reg_nn_custom.py``): a filled disc of radius 1 labelled ``+1``, surrounded
by an annular band ``r in [2.3, 3.0]`` labelled ``-1``. The *generative rule*
is purely radial, hence exactly SO(2)-invariant, but the band is only sampled
over a 90-degree wedge (``outer_arc_degrees``, the paper's setting), so the
training set itself is nowhere near rotation-symmetric. Whether the learned
classifier is rotation-invariant on the remaining 270 degrees is therefore a
genuine, non-tautological question about what the model picked up -- which is
exactly the setting the functional-sensitivity machinery in
``sensitivity_tools.py`` is meant to interrogate (does the tangent space
``T_theta = Im(J_theta)`` contain the direction ``X_rot f`` generated by the
SO(2) orbit?).

This script deliberately runs *only* the unconstrained baseline: the plain
GELU MLP of the reference repo (``SimpleMLP``, its "Plain MLP" dashed curve),
with no rotation augmentation and no projection penalty (``lambda_G =
lambda_perp = 0``), so any symmetry it exhibits is emergent rather than
imposed. It trains that model and draws the decision boundary in the reference
repo's plot style at initialisation and after training.

Alongside the figure it writes ``checkpoints.pt`` (the *same* initial and final
parameters, plus the dataset), so the follow-up tangent-space probe can be run
on this exact pair without retraining.

Usage:
    python aep_core_annulus_mlp.py
    python aep_core_annulus_mlp.py --outer-arc-degrees 360 --epochs 2000
"""

from __future__ import annotations

import argparse
import copy
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

from experiment_common import apply_config_overrides, select_device, select_dtype
from sensitivity_tools import participation_ratio


@dataclass
class Config:
    seed: int = 42
    device: str = "auto"
    dtype: str = "float32"
    output_dir: str = "outputs/aep_core_annulus_mlp"

    # ---- data (reference repo defaults; data_seed=3 is the paper figure's) ----
    data_seed: int = 3
    n_inner: int = 100
    n_outer: int = 100
    r_inner: float = 1.0
    r_outer_min: float = 2.3
    r_outer_max: float = 3.0
    # Angular extent of the outer band, centred on theta=0. The reference
    # implementation samples theta_out in [-pi/4, pi/4], i.e. 90 degrees; set
    # to 360 for a fully rotation-symmetric annulus (an exactly invariant
    # training set, useful as the control condition).
    outer_arc_degrees: float = 90.0

    # ---- model: the reference repo's plain MLP baseline ----
    hidden_dim: int = 96
    depth: int = 4

    # ---- optimisation: no augmentation and no projection penalty ----
    epochs: int = 200
    learning_rate: float = 3e-3
    # L1 penalty ``l1_weight * sum(|theta_i|)`` over every parameter, following
    # the same convention as experiment_common.run_training_loop. Not an
    # equivariance penalty: it is an architecture-agnostic sparsity pressure,
    # included here to test the sec. 8b question -- whether squeezing out
    # redundant capacity makes an unconstrained network's parameters line up
    # better with the symmetry directions than they do on their own.
    l1_weight: float = 0.0

    # ---- diagnostics / plotting ----
    invariance_rotations: int = 40
    plot_limit: float = 4.0
    plot_grid: int = 300
    plot_levels: int = 8


# --------------------------------- data ---------------------------------
def generate_data(cfg: Config) -> tuple[np.ndarray, np.ndarray]:
    """Filled unit disc (label +1) inside an annular band wedge (label -1).

    Kept bit-for-bit compatible with the reference repo at
    ``outer_arc_degrees=90``: the same number of draws is taken from the same
    generator in the same order, so ``data_seed=3`` reproduces the exact point
    cloud of the paper's Figure 4.
    """
    rng = np.random.default_rng(cfg.data_seed)

    theta_in = 2 * np.pi * rng.random(cfg.n_inner)
    # sqrt makes the disc uniformly dense rather than concentrated at the centre
    rad_in = cfg.r_inner * np.sqrt(rng.random(cfg.n_inner))
    x_inner = np.c_[rad_in * np.cos(theta_in), rad_in * np.sin(theta_in)]

    arc = math.radians(cfg.outer_arc_degrees)
    theta_out = arc * (rng.random(cfg.n_outer) - 0.5)
    rad_out = rng.uniform(cfg.r_outer_min, cfg.r_outer_max, cfg.n_outer)
    x_outer = np.c_[rad_out * np.cos(theta_out), rad_out * np.sin(theta_out)]

    x = np.vstack([x_inner, x_outer]).astype(np.float32)
    y = np.hstack([np.ones(cfg.n_inner), -np.ones(cfg.n_outer)]).astype(np.int64)
    return x, y


# --------------------------------- model ---------------------------------
class SimpleMLP(nn.Module):
    """The reference repo's unconstrained baseline: ``depth`` Linear layers, GELU between."""

    def __init__(self, hidden_dim: int = 96, depth: int = 4):
        super().__init__()
        layers: list[nn.Module] = [nn.Linear(2, hidden_dim), nn.GELU()]
        for _ in range(max(0, depth - 2)):
            layers.extend([nn.Linear(hidden_dim, hidden_dim), nn.GELU()])
        layers.append(nn.Linear(hidden_dim, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# ------------------------------- training -------------------------------
def train(
    model: nn.Module,
    x: np.ndarray,
    y: np.ndarray,
    cfg: Config,
    device: torch.device,
    dtype: torch.dtype,
) -> dict[str, list[float]]:
    """Full-batch Adam on BCE (+ optional L1) -- no equivariance penalty, no augmentation.

    The BCE term is recorded separately from the optimised objective so runs at
    different ``l1_weight`` stay comparable on the fit alone.
    """
    x_t = torch.tensor(x, device=device, dtype=dtype)
    y_t = torch.tensor((y > 0).astype(np.float32), device=device, dtype=dtype)[:, None]

    optimiser = optim.Adam(model.parameters(), lr=cfg.learning_rate)
    loss_fn = nn.BCEWithLogitsLoss()

    history: dict[str, list[float]] = {"bce": [], "objective": []}
    report_every = max(1, cfg.epochs // 10)
    for epoch in range(cfg.epochs):
        optimiser.zero_grad()
        bce = loss_fn(model(x_t), y_t)
        objective = bce
        if cfg.l1_weight > 0:
            objective = objective + cfg.l1_weight * sum(p.abs().sum() for p in model.parameters())
        objective.backward()
        optimiser.step()
        history["bce"].append(float(bce.detach()))
        history["objective"].append(float(objective.detach()))
        if epoch % report_every == 0 or epoch == cfg.epochs - 1:
            print(f"  epoch {epoch:5d}  bce = {history['bce'][-1]:.3e}"
                  f"  objective = {history['objective'][-1]:.3e}")
    return history


@torch.no_grad()
def accuracy(model: nn.Module, x: np.ndarray, y: np.ndarray, device, dtype) -> float:
    logits = model(torch.tensor(x, device=device, dtype=dtype))
    return float(np.mean((logits.cpu().numpy().ravel() > 0.0) == (y > 0)))


@torch.no_grad()
def invariance_error(
    model: nn.Module, x: np.ndarray, cfg: Config, device, dtype
) -> tuple[float, float]:
    """Mean and max ``|f(R_a x) - f(x)|`` over random rotations (the repo's ``E(T)``).

    This is the *function-level* symmetry defect: it sees only model outputs.
    The complementary, parameter-level question -- whether the orbit direction
    lies in the model's functional tangent space -- is what
    ``sensitivity_tools.tangent_projection`` answers.
    """
    pts = torch.tensor(x, device=device, dtype=dtype)
    base = model(pts)

    errors = []
    for _ in range(cfg.invariance_rotations):
        alpha = 2 * math.pi * torch.rand((), device=device).item()
        rotation = torch.tensor(
            [[math.cos(alpha), -math.sin(alpha)], [math.sin(alpha), math.cos(alpha)]],
            device=device,
            dtype=dtype,
        )
        errors.append((model(pts @ rotation.T) - base).abs())
    stacked = torch.stack(errors)
    return float(stacked.mean()), float(stacked.max())


@torch.no_grad()
def rotated_accuracy(model, x: np.ndarray, y: np.ndarray, cfg: Config, device, dtype) -> float:
    """Accuracy on randomly rotated copies of the data.

    The true labelling rule depends on ``|x|`` alone, so a rotation preserves
    every label: this measures whether the classifier generalises around the
    orbit, i.e. onto the 270 degrees of the annulus that carry no data.
    """
    generator = np.random.default_rng(cfg.data_seed + 1)
    scores = []
    for _ in range(cfg.invariance_rotations):
        alpha = 2 * math.pi * generator.random()
        rotation = np.array(
            [[math.cos(alpha), -math.sin(alpha)], [math.sin(alpha), math.cos(alpha)]],
            dtype=np.float32,
        )
        scores.append(accuracy(model, x @ rotation.T, y, device, dtype))
    return float(np.mean(scores))


# ------------------------------- plotting -------------------------------
def decision_grid(limit: float, resolution: int, device, dtype) -> tuple:
    """Evaluation mesh shared by every decision-boundary panel."""
    axis = np.linspace(-limit, limit, resolution)
    xx, yy = np.meshgrid(axis, axis)
    points = torch.tensor(
        np.c_[xx.ravel(), yy.ravel()].astype(np.float32), device=device, dtype=dtype
    )
    return xx, yy, points


def draw_decision_panel(
    ax, model: nn.Module, mesh: tuple, x: np.ndarray, y: np.ndarray, *, n_levels: int = 8
) -> np.ndarray:
    """Draw one panel in the reference repo's style: sign regions, black zero level, coolwarm level sets.

    Level-set values come from the 5th/95th percentiles of *this* panel's own
    scores, because networks at different points of training (or of a parameter
    walk) differ in output scale by orders of magnitude, and a shared
    normalisation would leave some panels blank.
    """
    xx, yy, points = mesh
    with torch.no_grad():
        score = model(points).float().cpu().numpy().reshape(xx.shape)

    ax.contourf(
        xx, yy, np.sign(score), levels=[-1, 0, 1],
        colors=["#ffdddd", "#ddddff"], alpha=0.5,
    )
    ax.contour(xx, yy, score, levels=[0], colors="black", linewidths=1.5)

    vmin, vmax = np.percentile(score, [5, 95])
    if abs(vmax - vmin) < 1e-2:  # near-constant output (typical at init)
        vmax = vmin + 1e-2
    levels = np.linspace(vmin, vmax, 2 * n_levels + 1)[1:-1]
    ax.contour(
        xx, yy, score, levels=levels, linewidths=1.0, cmap=plt.get_cmap("coolwarm"),
        norm=mcolors.Normalize(vmin=vmin, vmax=vmax), alpha=0.9, zorder=1,
    )

    positive, negative = y > 0, y < 0
    ax.scatter(x[positive, 0], x[positive, 1], c="blue", edgecolors="k", s=20, zorder=10)
    ax.scatter(
        x[negative, 0], x[negative, 1], c="red", edgecolors="k",
        marker="X", s=30, zorder=10,
    )

    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    return score


def plot_decision_boundaries(
    models: list[nn.Module],
    titles: list[str],
    annotations: list[str],
    x: np.ndarray,
    y: np.ndarray,
    cfg: Config,
    device,
    dtype,
    output_dir: Path,
) -> None:
    """One row of decision-boundary panels, in the reference repo's style."""
    mesh = decision_grid(cfg.plot_limit, cfg.plot_grid, device, dtype)

    fig, axes = plt.subplots(
        1, len(models), figsize=(4.5 * len(models), 4.8), constrained_layout=True
    )
    axes = np.atleast_1d(axes)

    for ax, model, title, annotation in zip(axes, models, titles, annotations):
        draw_decision_panel(ax, model, mesh, x, y, n_levels=cfg.plot_levels)
        ax.set_title(title, fontsize=17, pad=10)
        ax.text(
            0.5, -0.02, annotation, ha="center", va="top",
            fontsize=15, transform=ax.transAxes,
        )

    for suffix in ("png", "pdf"):
        fig.savefig(output_dir / f"decision_boundary_before_after.{suffix}", dpi=300)
    plt.close(fig)


# --------------------------------- main ---------------------------------
def parse_args() -> tuple[Config, argparse.Namespace]:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=None, help="JSON config overrides")
    parser.add_argument("--seed", type=int)
    parser.add_argument("--data-seed", type=int)
    parser.add_argument("--outer-arc-degrees", type=float)
    parser.add_argument("--epochs", type=int)
    parser.add_argument("--learning-rate", type=float)
    parser.add_argument("--hidden-dim", type=int)
    parser.add_argument("--depth", type=int)
    parser.add_argument("--l1-weight", type=float)
    parser.add_argument("--device", type=str)
    parser.add_argument("--output-dir", type=str)
    args = parser.parse_args()

    cfg = Config()
    apply_config_overrides(cfg, args.config)
    for field_name in ("seed", "data_seed", "outer_arc_degrees", "epochs", "l1_weight",
                       "learning_rate", "hidden_dim", "depth", "device", "output_dir"):
        value = getattr(args, field_name)
        if value is not None:
            setattr(cfg, field_name, value)
    return cfg, args


def main() -> None:
    cfg, _ = parse_args()
    torch.manual_seed(cfg.seed)
    np.random.seed(cfg.seed)

    device = select_device(cfg.device)
    dtype = select_dtype(cfg.dtype)
    output_dir = Path(cfg.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    x, y = generate_data(cfg)
    print(f"data: {len(x)} points ({int((y > 0).sum())} core / {int((y < 0).sum())} annulus), "
          f"outer arc {cfg.outer_arc_degrees:g} deg")

    model = SimpleMLP(hidden_dim=cfg.hidden_dim, depth=cfg.depth).to(device=device, dtype=dtype)
    initial_model = copy.deepcopy(model).eval()

    print(f"training plain MLP (hidden {cfg.hidden_dim}, depth {cfg.depth}) on {device}")
    history = train(model, x, y, cfg, device, dtype)
    model.eval()

    metrics = {}
    for label, net in (("initial", initial_model), ("trained", model)):
        mean_error, max_error = invariance_error(net, x, cfg, device, dtype)
        magnitudes = torch.cat([p.detach().abs().reshape(-1) for p in net.parameters()])
        metrics[label] = {
            "accuracy": accuracy(net, x, y, device, dtype),
            "rotated_accuracy": rotated_accuracy(net, x, y, cfg, device, dtype),
            "invariance_error_mean": mean_error,
            "invariance_error_max": max_error,
            "parameter_l1": float(magnitudes.sum()),
            "parameter_l2": float(torch.linalg.vector_norm(magnitudes)),
            # Effective number of parameters carrying the weight mass -- the
            # sparsity summary from sensitivity_tools.participation_ratio, which
            # stays meaningful when L1 leaves nothing exactly zero.
            "parameter_participation_ratio": participation_ratio(magnitudes.cpu().numpy()),
        }
        print(f"{label:>8s}: acc = {metrics[label]['accuracy']:.3f}  "
              f"rotated acc = {metrics[label]['rotated_accuracy']:.3f}  "
              f"E(T) = {max_error:.3e} (max)  {mean_error:.3e} (mean)  "
              f"|theta|_1 = {metrics[label]['parameter_l1']:.1f}  "
              f"PR(theta) = {metrics[label]['parameter_participation_ratio']:.0f}")

    annotations = [
        "acc = {accuracy:.2f},  ".format(**metrics[label])
        + "$\\mathcal{E}(T)$" + " = {invariance_error_max:.2e}".format(**metrics[label])
        for label in ("initial", "trained")
    ]
    plot_decision_boundaries(
        [initial_model, model],
        ["Before training (random init)", f"After training ({cfg.epochs} epochs)"],
        annotations,
        x, y, cfg, device, dtype, output_dir,
    )

    torch.save(
        {
            "config": asdict(cfg),
            "initial_state_dict": initial_model.state_dict(),
            "final_state_dict": model.state_dict(),
            "x": x,
            "y": y,
        },
        output_dir / "checkpoints.pt",
    )
    (output_dir / "result.json").write_text(
        json.dumps(
            {"config": asdict(cfg), "metrics": metrics,
             "final_bce": history["bce"][-1], "final_objective": history["objective"][-1],
             "loss_history": history},
            indent=2,
        )
    )
    print(f"wrote {output_dir}/decision_boundary_before_after.png, checkpoints.pt, result.json")


if __name__ == "__main__":
    main()
